version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie-node-browsers
    working_directory: ~/app
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b8:c9:bd:e1:1c:ba:6f:56:6a:ee:21:4d:a7:eb:c9:86"
      - checkout
      - setup_remote_docker
      - run: 
          name: Install AWSCLI
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: "Log in to AWS ECR"
          command: eval $(aws ecr get-login --no-include-email --region us-west-1)
      - run:
          name: "Build & Push Docker Image"
          command: |
            docker build -t hello_world .
            docker tag hello_world:latest 815280425737.dkr.ecr.us-west-1.amazonaws.com/ankr_ecr:hello_world
            docker push 815280425737.dkr.ecr.us-west-1.amazonaws.com/ankr_ecr:hello_world
      - run:
          name: "Pull Image on Docker Deployment Machine and Run on a new EC2 instance"
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@54.219.168.46 "./deploy.sh"
